name: faultmap
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cython=0.28.2=py36h14c3975_0
  - decorator=4.3.0=py36_0
  - h5py=2.7.1=py36h3585f63_0
  - hdf5=1.10.1=h9caa474_1
  - intel-openmp=2018.0.0=8
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - llvmlite=0.22.0=py36ha27ea49_0
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - ncurses=6.1=hf484d3e_0
  - networkx=2.1=py36_0
  - nose=1.3.7=py36hcdf7029_2
  - numba=0.37.0=np114py36h5fcf951_0
  - numpy=1.14.2=py36hdbf6ddf_1
  - openssl=1.0.2o=h20670df_0
  - pandas=0.23.0=py36h637b7d7_0
  - pip=10.0.1=py36_0
  - python=3.6.5=hc3d631a_2
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - readline=7.0=ha6073c6_4
  - scikit-learn=0.19.1=py36h7aa7ec6_0
  - scipy=1.1.0=py36hfc37229_0
  - setuptools=39.1.0=py36_0
  - six=1.11.0=py36h372c433_1
  - sqlite=3.23.1=he433501_0
  - tk=8.6.7=hc745277_3
  - wheel=0.31.1=py36_0
  - xz=5.2.3=h5e939de_4
  - zlib=1.2.11=ha838bed_2
  - pip:
    - appdirs==1.4.3
    - attrs==18.2.0
    - black==18.9b0
    - click==7.0
    - control==0.7.0
    - cycler==0.10.0
    - dill==0.2.7.1
    - jpype1==0.6.3
    - kiwisolver==1.0.1
    - matplotlib==3.0.2
    - multiprocess==0.70.5
    - numexpr==2.6.5
    - pathos==0.2.1
    - pox==0.2.3
    - ppft==1.6.4.7.1
    - pyparsing==2.2.0
    - tables==3.4.3
    - toml==0.10.0
